- hosts: all
  remote_user: ec2-user
  tasks:
   
   - name : Create a File
     file:
      path: "/home/{{ ansible_user }}/test_file1"
      state: touch

   - name: Fetch test_file1 
     fetch:
      src: "/home/{{ ansible_user }}/test_file1"
      dest: fetched  