- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    
    - name: Run command with shell
      shell: echo "Hello ICU Shell" > /tmp/shell_file
      register: shell_file 

    - name: Run command with command 
      command: echo "Hello ICU Command" > /tmp/command_file
      register: command_file 

    - name: Debug
      debug: vars=shell_file

    - name: Debug 
      debug: vars=command_file      