- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
   
   - name: Creating Multiple Directories
     file:
      path: "/tmp/{{ item }}"
      state: directory

     loop:
      - test_dir1
      - test_dir2
      - test_dir3 