- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
   
   - name: Create a directory
     file: 
      path: /etc/test_dir
      state: directory

   - name: Remove directory
     file: 
      path: /etc/test_dir
      state: absent   