- hosts: all
  remote_user: ec2-user
  tasks:
   
   - name : Create a File
     copy:
      dest: "/home/{{ ansible_user }}/test_file1"
      content: "{{ ansible_host }}"

   - name: Fetch test_file1 
     fetch:
      src: "/home/{{ ansible_user }}/test_file1"
      dest: "fetched/{{ inventory_hostname }}/"
      flat: true  